'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),overlay=document.getElementById('overlay'),scoreEl=document.getElementById('score'),sausageEl=document.getElementById('sausages'),bestEl=document.getElementById('best'),startButton=document.getElementById('start');
const W=960,H=540,keys=new Set();let state='ready',dog={x:215,y:260,vy:0},gates=[],sausages=[],particles=[],score=0,sausageScore=0,best=0,spawn=0,last=0,world=0,ready=false;
try{best=Number(localStorage.getItem('bichon-record'))||0}catch{}bestEl.textContent=best;
const sprite=new Image();sprite.onload=()=>{ready=true;startButton.disabled=false;startButton.textContent='¡Vamos a jugar!'};sprite.onerror=()=>{document.getElementById('message').textContent='No se pudo cargar el personaje. Comprueba la carpeta assets/images.'};sprite.src='assets/images/bichon-sprite.png';
function show(title,message,label){document.getElementById('title').textContent=title;document.getElementById('message').textContent=message;startButton.textContent=label;overlay.hidden=false}
function start(){if(!ready)return;state='playing';dog={x:215,y:260,vy:-290};gates=[];sausages=[];particles=[];score=0;sausageScore=0;spawn=.5;scoreEl.textContent=0;sausageEl.textContent=0;overlay.hidden=true;keys.clear();document.getElementById('pause').textContent='Pausar';document.getElementById('status').textContent='¡Busca el siguiente hueco y atrapa las salchichitas!';last=performance.now()}
function flap(){if(!ready)return;if(state==='ready'||state==='over'){start();return}if(state!=='playing')return;dog.vy=-310;for(let i=0;i<6;i++)particles.push({x:dog.x-18,y:dog.y+15,vx:-50-Math.random()*60,vy:(Math.random()-.5)*80,life:.5,type:'cloud'})}
function pause(){if(state==='playing'){state='paused';keys.clear();show('Una pequeña pausa','Tu aventura te espera.','Continuar');document.getElementById('pause').textContent='Continuar'}else if(state==='paused'){state='playing';overlay.hidden=true;last=performance.now();document.getElementById('pause').textContent='Pausar'}}
function die(){state='over';keys.clear();if(score>best){best=score;bestEl.textContent=best;try{localStorage.setItem('bichon-record',String(best))}catch{}}show('¡Otro saltito!',`Has conseguido ${score} ${score===1?'punto':'puntos'} y ${sausageScore} ${sausageScore===1?'salchicha':'salchichas'}. Tu récord: ${best}.`,'Volver a jugar');document.getElementById('status').textContent='Fin de la partida. Pulsa espacio para volver a intentarlo.'}
function circleRect(x,y,r,rx,ry,rw,rh){const dx=x-Math.max(rx,Math.min(x,rx+rw)),dy=y-Math.max(ry,Math.min(y,ry+rh));return dx*dx+dy*dy<r*r}
function collectSausage(s){s.collected=true;sausageScore++;sausageEl.textContent=sausageScore;document.getElementById('status').textContent=`¡Ñam! Llevas ${sausageScore} ${sausageScore===1?'salchicha':'salchichas'}.`;for(let i=0;i<10;i++)particles.push({x:s.x,y:s.y,vx:(Math.random()-.5)*150,vy:(Math.random()-.5)*150,life:.55,type:'sausage'})}
function update(dt){if(state!=='playing')return;world+=dt;const speed=175+Math.min(score*3,85);dog.x+=((keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0))*220*dt;dog.x=Math.max(40,Math.min(700,dog.x));dog.vy+=760*dt;dog.y+=(dog.vy+((keys.has('ArrowDown')?1:0)-(keys.has('ArrowUp')?1:0))*190)*dt;spawn-=dt;if(spawn<=0){const center=165+Math.random()*210,x=W+50;gates.push({x,center,passed:false});if(Math.random()<.82)sausages.push({x:x+36,y:center+(Math.random()-.5)*70,collected:false,wobble:Math.random()*Math.PI*2});spawn=1.95}const gap=190-Math.min(score,30);for(const gate of gates){gate.x-=speed*dt;const top=gate.center-gap/2,bottom=gate.center+gap/2;if(circleRect(dog.x,dog.y,22,gate.x-5,0,82,top)||circleRect(dog.x,dog.y,22,gate.x-5,bottom,82,H-bottom)){die();return}if(!gate.passed&&gate.x+77<dog.x-22){gate.passed=true;score++;scoreEl.textContent=score}}for(const s of sausages){s.x-=speed*dt;if(!s.collected&&Math.hypot(dog.x-s.x,dog.y-s.y)<37)collectSausage(s)}gates=gates.filter(g=>g.x>-100);sausages=sausages.filter(s=>s.x>-60&&!s.collected);if(dog.y<22||dog.y>H-42){die();return}for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt}particles=particles.filter(p=>p.life>0)}
function round(x,y,w,h,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function drawSausage(x,y,t,wobble=0){const bob=Math.sin(t/180+wobble)*4;ctx.save();ctx.translate(x,y+bob);ctx.rotate(Math.sin(t/260+wobble)*.12);ctx.fillStyle='#d96a49';ctx.strokeStyle='#8e3e30';ctx.lineWidth=3;ctx.beginPath();ctx.roundRect(-20,-8,40,16,8);ctx.fill();ctx.stroke();ctx.fillStyle='#f0aa73';ctx.beginPath();ctx.moveTo(-20,-4);ctx.lineTo(-27,-9);ctx.lineTo(-27,0);ctx.lineTo(-20,4);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(20,-4);ctx.lineTo(27,-9);ctx.lineTo(27,0);ctx.lineTo(20,4);ctx.closePath();ctx.fill();ctx.strokeStyle='#ffd6b5';ctx.lineWidth=2;ctx.beginPath();ctx.arc(-6,-2,7,3.7,5.35);ctx.stroke();ctx.restore()}
function draw(t){const sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#78c6eb');sky.addColorStop(.65,'#c8ebec');sky.addColorStop(1,'#ffe3b1');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff5';for(let i=0;i<22;i++){const x=((i*157-world*12)%1100+1100)%1100-70,y=45+(i*73)%370;ctx.beginPath();ctx.arc(x,y,2+(i%3),0,Math.PI*2);ctx.fill()}for(let i=0;i<6;i++){const x=((i*230-world*18)%1300+1300)%1300-170;round(x,70+i%3*95,130,7,4,'#ffffff55')}const gap=190-Math.min(score,30);for(const gate of gates){const top=gate.center-gap/2,bottom=gate.center+gap/2;round(gate.x,-20,72,top+20,12,'#247d8c');round(gate.x+8,0,12,top,5,'#72c5c5');round(gate.x-5,top-18,82,18,6,'#185965');round(gate.x,bottom,72,H-bottom,12,'#247d8c');round(gate.x+8,bottom+18,12,H-bottom,5,'#72c5c5');round(gate.x-5,bottom,82,18,6,'#185965');ctx.fillStyle='#ffffff66';ctx.font='bold 18px system-ui';ctx.fillText('✦',gate.x+27,top-35)}for(const s of sausages)if(!s.collected)drawSausage(s.x,s.y,t,s.wobble);ctx.fillStyle='#183f5f';ctx.fillRect(0,H-18,W,18);ctx.fillStyle='#4e8d99';ctx.fillRect(0,H-22,W,4);for(let i=0;i<40;i++)round((i*40-world*100)%1600,H-12,20,3,2,'#ffffff20');for(const p of particles){ctx.globalAlpha=Math.max(0,p.life*1.5);if(p.type==='sausage'){ctx.fillStyle='#ffd17b';ctx.beginPath();ctx.arc(p.x,p.y,4,0,Math.PI*2);ctx.fill()}else{ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(p.x,p.y,5*p.life,0,7);ctx.fill()}}ctx.globalAlpha=1;if(ready){ctx.save();ctx.translate(dog.x,state==='ready'?dog.y+Math.sin(t/350)*8:dog.y);ctx.rotate(state==='playing'?Math.max(-.22,Math.min(.45,dog.vy/1100)):0);ctx.drawImage(sprite,-44,-44,88,88);ctx.restore()}if(state==='playing'){ctx.fillStyle='#183f5f55';ctx.font='800 72px system-ui';ctx.textAlign='center';ctx.fillText(score,W/2,84);ctx.font='700 22px system-ui';ctx.textAlign='left';ctx.fillStyle='#183f5fcc';ctx.fillText(`🌭 ${sausageScore}`,24,42)}ctx.textAlign='left'}
function frame(t){const dt=Math.min((t-last)/1000||0,1/30);last=t;update(dt);draw(t);requestAnimationFrame(frame)}requestAnimationFrame(frame);
document.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)){e.preventDefault();if(e.code==='Space'){if(!e.repeat)flap()}else keys.add(e.code)}if(e.code==='KeyP'&&!e.repeat)pause()});document.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();if(state==='playing')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')pause()});startButton.onclick=()=>state==='paused'?pause():start();document.getElementById('restart').onclick=start;document.getElementById('pause').onclick=pause;document.getElementById('jump').onpointerdown=e=>{e.preventDefault();flap()};canvas.onpointerdown=e=>{e.preventDefault();flap()};for(const b of document.querySelectorAll('[data-key]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key)};b.onpointerup=b.onpointercancel=()=>keys.delete(b.dataset.key)}