'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),overlay=document.getElementById('overlay'),scoreEl=document.getElementById('score'),sausageEl=document.getElementById('sausages'),bestEl=document.getElementById('best'),startButton=document.getElementById('start'),stage=document.getElementById('stage'),main=document.querySelector('main');
const W=960,H=540;let state='ready',dog={x:215,y:260,vy:0},gates=[],sausages=[],particles=[],score=0,sausageScore=0,best=0,spawn=0,last=0,world=0,ready=false;
const isMobile=window.matchMedia('(pointer: coarse)').matches||/Android|iPhone|iPad|iPod|Mobile/i.test(navigator.userAgent);
if(isMobile){main.classList.add('mobile-mode');document.getElementById('mobile-help').hidden=false;document.getElementById('desktop-help').hidden=true;}
try{best=Number(localStorage.getItem('bichon-record'))||0}catch{}bestEl.textContent=best;

// Audio original generado en el navegador con Web Audio: no usa grabaciones ni música de terceros.
// En iPhone/iPad Safari el contexto debe desbloquearse directamente desde un gesto del usuario.
let audioCtx=null,musicTimer=null,musicStep=0,musicToken=0;
const melody=[523.25,659.25,783.99,659.25,587.33,698.46,880,698.46,523.25,659.25,783.99,1046.5,880,783.99,659.25,587.33];
function getAudioContext(){if(!audioCtx){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null;audioCtx=new AC()}return audioCtx}
async function unlockAudio(){const ac=getAudioContext();if(!ac)return false;try{const buffer=ac.createBuffer(1,1,22050),source=ac.createBufferSource(),gain=ac.createGain();gain.gain.value=0;source.buffer=buffer;source.connect(gain);gain.connect(ac.destination);source.start(0)}catch{}try{if(ac.state==='suspended')await ac.resume()}catch{}return ac.state==='running'}
function tone(freq,duration=.12,volume=.05,type='sine',when=0){if(!audioCtx||audioCtx.state!=='running')return;const now=audioCtx.currentTime+when,o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,now);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(volume,now+.012);g.gain.exponentialRampToValueAtTime(.0001,now+duration);o.connect(g);g.connect(audioCtx.destination);o.start(now);o.stop(now+duration+.02)}
function musicTick(){if(state!=='playing'||!audioCtx||audioCtx.state!=='running')return;const n=melody[musicStep%melody.length];tone(n,.22,.022,'triangle');if(musicStep%2===0)tone(n/2,.3,.012,'sine');musicStep++}
function stopMusic(){musicToken++;if(musicTimer){clearInterval(musicTimer);musicTimer=null}}
function startMusic(){stopMusic();const token=musicToken;musicStep=0;unlockAudio().then(ok=>{if(!ok||token!==musicToken||state!=='playing')return;musicTick();musicTimer=setInterval(musicTick,260)})}
function sausageSound(){unlockAudio().then(ok=>{if(!ok)return;tone(880,.09,.07,'square');tone(1174.66,.11,.055,'square',.07);tone(1567.98,.14,.045,'triangle',.14)})}
function gameOverSound(){stopMusic();unlockAudio().then(ok=>{if(!ok)return;tone(392,.18,.06,'triangle');tone(329.63,.22,.06,'triangle',.16);tone(261.63,.35,.07,'triangle',.34)})}

const sprite=new Image();sprite.onload=()=>{ready=true;startButton.disabled=false;startButton.textContent=isMobile?'Jugar en horizontal':'¡Vamos a jugar!';if(isMobile&&matchMedia('(orientation: portrait)').matches){document.getElementById('title').textContent='Gira el móvil';document.getElementById('message').innerHTML='Pon el teléfono en <span class="rotate-hint">horizontal</span> y toca el botón para jugar. Después solo tendrás que tocar la pantalla para saltar.'}};sprite.onerror=()=>{document.getElementById('message').textContent='No se pudo cargar el personaje.'};sprite.src='assets/images/bichon-sprite.png?v=4';
const sausageSprite=new Image();sausageSprite.src='assets/images/sausage-first.png?v=10';
function show(a,b,c){document.getElementById('title').textContent=a;document.getElementById('message').textContent=b;startButton.textContent=c;overlay.hidden=false}
async function enterMobilePlay(){if(!isMobile)return;try{if(!document.fullscreenElement&&stage.requestFullscreen)await stage.requestFullscreen()}catch{}try{if(screen.orientation&&screen.orientation.lock)await screen.orientation.lock('landscape')}catch{}}
function start(){if(!ready)return;state='playing';dog={x:215,y:260,vy:-290};gates=[];sausages=[];particles=[];score=sausageScore=0;spawn=.5;scoreEl.textContent=sausageEl.textContent=0;overlay.hidden=true;document.getElementById('pause').textContent='Pausar';last=performance.now();startMusic()}
function flap(){if(!ready)return;if(state==='ready'||state==='over'){start();return}if(state!=='playing')return;dog.vy=-310;for(let i=0;i<6;i++)particles.push({x:dog.x-18,y:dog.y+15,vx:-50-Math.random()*60,vy:(Math.random()-.5)*80,life:.5,type:'cloud'})}
function pause(){if(state==='playing'){state='paused';stopMusic();show('Una pequeña pausa','Tu aventura te espera.','Continuar');document.getElementById('pause').textContent='Continuar'}else if(state==='paused'){state='playing';overlay.hidden=true;last=performance.now();document.getElementById('pause').textContent='Pausar';startMusic()}}
function die(){if(state==='over')return;state='over';gameOverSound();if(score>best){best=score;bestEl.textContent=best;try{localStorage.setItem('bichon-record',String(best))}catch{}}show('¡Otro saltito!',`Has conseguido ${score} puntos y ${sausageScore} salchichas. Tu récord: ${best}.`,isMobile?'Toca para volver a jugar':'Volver a jugar')}
function circleRect(x,y,r,rx,ry,rw,rh){const dx=x-Math.max(rx,Math.min(x,rx+rw)),dy=y-Math.max(ry,Math.min(y,ry+rh));return dx*dx+dy*dy<r*r}
function collectSausage(s){s.collected=true;sausageScore++;sausageEl.textContent=sausageScore;sausageSound();for(let i=0;i<10;i++)particles.push({x:s.x,y:s.y,vx:(Math.random()-.5)*150,vy:(Math.random()-.5)*150,life:.55,type:'sausage'})}
function update(dt){if(state!=='playing')return;world+=dt;const speed=175+Math.min(score*3,85);dog.vy+=760*dt;dog.y+=dog.vy*dt;spawn-=dt;if(spawn<=0){const center=165+Math.random()*210,x=W+50;gates.push({x,center,passed:false});if(Math.random()<.82)sausages.push({x:x+36,y:center+(Math.random()-.5)*70,collected:false,wobble:Math.random()*Math.PI*2});spawn=1.95}const gap=190-Math.min(score,30);for(const g of gates){g.x-=speed*dt;const top=g.center-gap/2,bottom=g.center+gap/2;if(circleRect(dog.x,dog.y,22,g.x-5,0,82,top)||circleRect(dog.x,dog.y,22,g.x-5,bottom,82,H-bottom)){die();return}if(!g.passed&&g.x+77<dog.x-22){g.passed=true;score++;scoreEl.textContent=score}}for(const s of sausages){s.x-=speed*dt;if(!s.collected&&Math.hypot(dog.x-s.x,dog.y-s.y)<42)collectSausage(s)}gates=gates.filter(g=>g.x>-100);sausages=sausages.filter(s=>s.x>-80&&!s.collected);if(dog.y<22||dog.y>H-42){die();return}for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt}particles=particles.filter(p=>p.life>0)}
function round(x,y,w,h,r,c){ctx.fillStyle=c;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function drawSausage(x,y,t,w=0){ctx.save();ctx.translate(x,y+Math.sin(t/180+w)*5);ctx.rotate(Math.sin(t/260+w)*.12);if(sausageSprite.complete&&sausageSprite.naturalWidth){const width=74,height=52;ctx.drawImage(sausageSprite,-width/2,-height/2,width,height)}ctx.restore()}
function draw(t){const sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#78c6eb');sky.addColorStop(.65,'#c8ebec');sky.addColorStop(1,'#ffe3b1');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);const gap=190-Math.min(score,30);for(const g of gates){const top=g.center-gap/2,bottom=g.center+gap/2;round(g.x,-20,72,top+20,12,'#247d8c');round(g.x-5,top-18,82,18,6,'#185965');round(g.x,bottom,72,H-bottom,12,'#247d8c');round(g.x-5,bottom,82,18,6,'#185965')}for(const s of sausages)if(!s.collected)drawSausage(s.x,s.y,t,s.wobble);ctx.fillStyle='#183f5f';ctx.fillRect(0,H-18,W,18);for(const p of particles){ctx.globalAlpha=Math.max(0,p.life*1.5);ctx.fillStyle=p.type==='sausage'?'#ffd17b':'#fff';ctx.beginPath();ctx.arc(p.x,p.y,4,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;if(ready){ctx.save();ctx.translate(dog.x,state==='ready'?dog.y+Math.sin(t/350)*8:dog.y);ctx.rotate(state==='playing'?Math.max(-.22,Math.min(.45,dog.vy/1100)):0);ctx.drawImage(sprite,-44,-44,88,88);ctx.restore()}if(state==='playing'){ctx.fillStyle='#183f5f55';ctx.font='800 72px system-ui';ctx.textAlign='center';ctx.fillText(score,W/2,84);ctx.font='700 22px system-ui';ctx.textAlign='left';ctx.fillStyle='#183f5fcc';ctx.fillText(`🌭 ${sausageScore}`,24,42)}ctx.textAlign='left'}
function frame(t){const dt=Math.min((t-last)/1000||0,1/30);last=t;update(dt);draw(t);requestAnimationFrame(frame)}requestAnimationFrame(frame);
document.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();if(!e.repeat){unlockAudio();flap()}}if(e.code==='KeyP'&&!e.repeat)pause()});window.addEventListener('blur',()=>{if(state==='playing'&&!isMobile)pause()});
startButton.addEventListener('pointerdown',()=>{unlockAudio()},{passive:true});startButton.addEventListener('touchstart',()=>{unlockAudio()},{passive:true});
startButton.onclick=async()=>{unlockAudio();if(isMobile)await enterMobilePlay();if(state==='paused')pause();else start()};document.getElementById('restart').onclick=()=>{unlockAudio();start()};document.getElementById('pause').onclick=()=>{unlockAudio();pause()};canvas.onpointerdown=e=>{e.preventDefault();unlockAudio();flap()};
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopMusic();else if(state==='playing')startMusic()});
window.addEventListener('pageshow',()=>{if(state==='playing')startMusic()});
window.addEventListener('orientationchange',()=>{if(isMobile&&matchMedia('(orientation: portrait)').matches&&state!=='playing')show('Gira el móvil','Pon el teléfono en horizontal. Después toca el botón y juega tocando la pantalla.','Jugar en horizontal')});